got stdin
 On branch main
 Changes to be committed:
	modified:   README
	modified:   be-as

diff --git a/be-as b/be-as
--- a/be-as
+++ b/be-as
@@ -2,13 +2,10 @@
 
 # be-as: POC (no data validation) assembler for Ben Eater's 8-bit computer
 
-if (( $# == 0 )) ; then
-  builtin echo input file required >&2
-  exit 1
-fi
+noarg=___
 
 # label => "name:"
-declare -A syms=( [_]= ) OPS=(
+declare -A syms=( [$noarg]= ) OPS=(
   [NOP]=0
   [LDA]=1
   [ADD]=2
@@ -24,36 +21,40 @@ declare -A syms=( [_]= ) OPS=(
 
 hex=( {0..9} {a..f} )
 
+in="${1:-/dev/stdin}"
+
 # build symbol table
 addr=0
 while read line ; do
   if [[ "$line" =~ : ]] ; then
-    if [[ "$line" =~ [[:space:]]*_: ]] ; then
-      builtin echo "sorry, can't use _ as a symbol :\\" >&2
+    if [[ "$line" =~ [[:space:]]*$noarg: ]] ; then
+      builtin echo "can't use $noarg as a symbol :\\" >&2
       exit 1
     fi
-    syms[${line%:*}]=$addr
+    toks=( $line )  # this should be a function for a uniform API, see below
+    sym=${toks[0]%:*}
+    syms[$sym]=$addr
   else
     ((addr++))
   fi
-done < $1
+done < "$in"
 
 # assemble image
 addr=0
 image=
 while read line ; do
-  if [[ ! "$line" =~ : ]] ; then
+  if ! [[ "$line" =~ : ]] ; then
     toks=( $line )
     optok=${toks[0]^^}
     op=${OPS[$optok]}
-    argtok=${toks[1]:-_}  # _ resolves to '' in the symbol table
-    sym=${syms[$argtok]}  # symbol?
-    lit=${sym:-$argtok}   # no? literal?
-    val=${lit:-0}         # no? no argument so use whatever (Ben used 0)
+    argtok=${toks[1]:-$noarg}  # $noarg resolves to '' in the symbol table
+    sym=${syms[$argtok]}       # symbol?
+    lit=${sym:-$argtok}        # no? literal?
+    val=${lit:-0}              # no? no argument so use whatever (Ben used 0)
     arg=${hex[$val]}
     image+='\x'"${hex[$((addr++))]}"  # address
     image+='\x'"$op$arg"              # command
   fi
-done < $1
+done < "$in"
 
 builtin echo -en $image
